language: node_js
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAJH7GF2IJUOBJ6LDQ
  secret_access_key:
    secure: gSFiKcbiJy+fFngJb1xmRifiPl7QVIYXKaR9innkrx/2DqhhMcCK317b4K60Ctg+dIA88TDzQxM/2XwE4p0KOE+qMbYymFXlr5sUD+jURxxSq/SnRZmvXWI7VioioFVIi9ri9IGUTgbUQBu+iK+JlUcd4o0AC5KnYOTuuEPYD/zaS4MOygiZPx5ztbFV8K3hFUJm9abFnvwjGkXxo4O67Cf2OvwOS8zp+GE1vwDFaTOQXxFXIELKIUOdpre9qNjyXmclAM5eDFlJpveESkcAcNGYa/qQi5sBvvnp6o4vivhLmDhWD5kBedDJ6e3V/zRXCNu80PauAnBeXaGEdzowjhTg7BsZMnZuHdDWQjIHUCkprQ9FnikDC3ofBBNq4ZbS3HClw67Or8vsKqJVTmpHbvPx+F/hIKkh3V9+lQxQ416YJRMRpPTq9sKBh1dxN4rltCojc1nyf+eDyj4rA+ef38LJpP0mm5uxFjSAktlw+92BDbHqyz4wc72OTTBCFQSfyGoJxJybFp6Da0QgSSa322EUy7l5e/kIQWDt5wxQcD26C6o4leDsC/jlyNLq6l4oA+eATYKRLofJrA//DtoAqD9fZwpKTQdIOLR8MOkwr/MiI8a9u3zJx3IZSUlvXkFdQVhN+yKf02Wgbd3ZN3cu2y+h8olVsT9zVog3XYanXUo=
  bucket: www.saulo.dev
  region: us-west-2
  local_dir: build
  skip_cleanup: true
