language: node_js
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: s3
  region: us-west-2
  local_dir: build
  access_key_id: AKIAJH7GF2IJUOBJ6LDQ
  secret_access_key:
    secure: W4JSle9UCBiawUBvsQvIvRiWHad6Am+utzL3c6+Fww7Lv9aVqzZtMnwNYuim758iwqr6EY6qzf/epon2xjn3OkMeu9AnYzM0cKRYQs+MlIerQ8EGlzK54O2qF7RBDj/i+SjClJTsmuyIg2UdHez5TccXNK8wuT9A/FIm1fINkq+xYVk4SbxDmJjGyn7vrPGgWhqXjbph1HVZ0o/4M24Wv7oyrlZfraOfouKmNU4rDHGAzUdnMhAP5r4wID125RA/vbQvD+1HYvNwdZl4mcnpAVmOyLuNQF6Jm84we9wqoMeY3RHvhy0LxjYP3axlDCqf6V3MBSAVy8cMhZzWG0iDaK0pkxcApQMcc4Dm+fJAUQ4sVsJxR6XelcZihpQ1epzUhF+XVi01XBMMYhh8xUp5RqTLQUKmPItYM9hTV0sCBokmEkEldRr6xjdBOjSB+2BrQG/0I8rCszHMfjn3BGTaVRKw3mlXP0kfXBnAz5oGKBR42pRhDmUhYpSmxxewUNXsW1oEMUsbtSOyPX2Q6d8dIP74BVftGdBPCfR1BnpYoRF6nK9MICF+HwubAqJ/zw1ITlablrhPQGuSa861kfTH9Raldg+rXJcO3Rb7D0yM02vRElM2StVx7nWkYQXNE1njpALF5r0dwYK8Ia0eIBlDJ8Uq3lF2tvRbuu7TB1d9hYU=
  skip_cleanup: true
  bucket: www.saulo.dev
  on:
    repo: Sauloxd/webvim
