language: node_js
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: s3
  region: us-west-2
  local_dir: build
  access_key_id: AKIAJH7GF2IJUOBJ6LDQ
  secret_access_key:
    secure: ffI/MRGVRST1Zk9hKjDBaJMnAiK8NTpy41lwdbCP7GNbWmNJ2T37wy/YruoUckIR5s6nqf39e1plopwCR7iBo+MNvPTq0aRFaHkjMM6Ot8WyZ4PcVuiQJc+a4DT0j00mt51l2zXjlsY8EItKYBriHiYmVpOakVE1yfAlVpeZn1hNFw6tSgDGYSAS+36jo+A0/AV5GfhEVXdtQrcHhorn8F3oarSL2uxgwdBqHUUCxrH8iWo98ovKIF/KYOZlrTIy4xR1qfIVX1eHgqUZIRobgOYDqkqnip7fUDoxopoyYphZLT3WN7muZzAUwcYztauxcGs3hz6Z3hKxVX80aa8ibSUIDRVpDDhQM2Dc6Sc5nX2fgrCutPUdDNHwa7Z5SpYpub1nlvI0wHh4tly57wIYSxPaG/SPoK6H8/GXiMXV6XvGd/ZrNpybFjieGu1+qyshNGBtiINmOdal4x3qGAOHR7q6ZGGW8OFo3fhb4Jfuo/XKvCBe5LSq/WtZgU7VRVTRNo1iyx5NbSv7gF4CdwxNH0wucy/+VbsatVBQKKVvunSToAYfIOOR9L41fR1q9UsqsZ5N+103vRJXT/6rZLlrA4mHCnlBFcDXmCZ/bKLHneVQEaytXRxa9Fc06Jc+ARhQ7lkCvCNeHC2zfktHYBEY6Ssdpdkf71aUsaC0Td7erhw=
  skip_cleanup: true
  bucket: www.saulo.dev
  on:
    repo: Sauloxd/webvim
