language: node_js
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
before_deploy: pip install --user awscli
deploy:
  provider: script
  script: "~/.local/bin/aws s3 sync build s3://www.saulo.dev --region=us-west-2 --delete"
  acl: public_read
  access_key_id: AKIAJH7GF2IJUOBJ6LDQ
  secret_access_key:
    secure: t4SqWRD2LgqWtGVeMcFfk6ervSGAL/+eQ0Jm6L2d5meIaRBudEFjPqz35ogj1n1tm+tMFWTuhnpUc/Ht+WiDWmXFomnGe34p5KjuycRp+0ozJpuDLMoJftaIfd2tvnoYmY7QFTbIEUkSJjZmyf1sb4gWn8XuY4cpw76a8VGJAiU/IP70gqVhFOB4g0twKZwDVtFwS58VlfOK2Ez/AI9wxO7W7krEON7dY1hfm2M3pvbXy1S08ePkDsz5WtI95d9gWML8eOfteVTPD7UicaXIKZMRfTACfXw/zT2172hji+m5frzE5zjjy4M3QWdng+r+Wm7ioevFUeGIEIYTpJklgpBfyv9t0LrlTNlZeUiOXxF9jPKdXf4XeM6ZzJ6XEQx7FutnCo/VaWhYfAZdlsUysc/i4p8c7LUM5cgPC8JkbYQvHxkiUnOXeunpI0Rh+fuc4mS8sC7KasAHmy34QGS6qXlOayt0SKwDBxjVGMPe05MklO41ENNj7lGP/69pVo8nXmqIuJnxVJRccYVPYA8e6x/Rn5sIQycuReX23gtl5XoHiDYvRwEoHyiDLXDv2RmzLJnz63EzBF3sbgXwfi3ZGreK5F5t/VyoRbtoCldeoU0nmtxGMKJTf0GyAgq9alvX8iX/i8yjVOCnMZqlifFF4Eku3eK08kf0ygJ+qNruLp8=
  bucket: www.saulo.dev
  region: us-west-2
  local_dir: build
  skip_cleanup: true
  on:
    branch: master
env:
  AWS_ACCESS_KEY_ID:
    secure: Yv35y42xAEeK0etIkawfWPnYMyVlroTFb29LC9zr7ziFwk5HZ4FZHjC+H0leMvTpi6xHxaWVKYw6fwf9Nct9jXQqghFaSgwRYl44tGOqV0d3v1wkjWyTXs1LirsHtoBkKscsE6tTUbcTX5wRPvWpH1ZVVJRm5B3k0za3Rtk9Q9WZiJCzkyvCNrAZpViCHs+Lg4WsNhQYh/Y/66SzpAe6U/6KOfscd6EhQeOmIjT/kWZDGg+StM5JTP7BSuhX9ZkT5QCYxpu5hR6BZhu1Yra8O8wAchF380vp3FTV7nzWDuYX9X2vaaJKnjXLTb2DBDM97pQ6RlqGkdJRmLVNzA0kUX3OMYlG24imO5QvKJWCFn+5iRhx+Q0b7OmKdFFAW4Mb3k508gpbAZSrxA+a9bL8Y10pOBMs4Hpip5bLzJKAmS9XHH86E/PqwYsqo47oem5pnqf3D7KcmF5w52XKMxkK3qRD/zG8M9S76uaNg8ydwyNGkmkulVuTxA4OKRw3FDMCMr1n2gEtUpQ7fgjxcM4JhRC9LnHSUrH49lU3Qv2A6R8SSSQenXJmvwjX07Zbo4IPu/KmfBDqbwuo1JO3YAEbvH5fYNN8mPmb538PHMK8ZVKrh/U5KsGEGgBj3qrYSIClIBb/zGANeSnUEDZAbyICgrYlROaDg/Ka6Mi2bC1zYsI=
  AWS_SECRET_ACCESS_KEY:
    secure: S8fL8CUMsRAQsVG8v1LMhGnLYunAisK9bmcOQHLj9yg4FgYi8jA+IW12EyAmEQDDOLgaXKOicB7kOoYwaSWYiDdVUP3Vgb/08SOk/VwuLRgLHWR2W5jZn9UFlWEZc6eLbA4EvdYbKugYoSrILeKBe2bmXy5GAHQBAwaBMNF+q7C3SOWA1Md1y3eV8hqfNOVe4DobQC0kJ1pmj2iepKgCLubF3b97BIomAwlSWkGFDumi2D9NvogHfczpeWbz22t8pg7zbAt0MgWu7SqAnzC6zCfVFOdVsfL5rYjH3oUwKAcRZa+qq5rk5OI0VDfU59RFipOiZimR4OvQRp/4vsWYvnJCCYoKgrOc7aEj8dLnzMbEyNxr/7c19xUNpLhgdvZF2tirVVnUjFLz50QVEnINTMnSaF0aVwj8hy2dlUa2tOVp/May/xanoBTk9mmiKV20c3cQGCWCIM0MaIUyapw7rcdMUdErFjIom0h9B7pgka3IkBjXyYOJanxbh3ZU+JwDufBCg8EqYfFSr0RRDeOfGXHGTFgWjdqCktpmKfh8M7dyqlaCfazB4KWxaNH8xawKGx5/vgcWkCbPtg+GqlFRPMCMBc8NqGaQ2abc1Ek3IAezvhQmN43k2ZYPtplHMlT2JDt3KyIk1M1fAuCEAfK2mpFwN/VW688m6MNEmTXuHKI=
