language: node_js
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
before_deploy: pip install --user awscli
deploy:
  provider: script
  script: "~/.local/bin/aws s3 sync build s3://www.saulo.dev --region=us-west-2 --delete"
  acl: public_read
  bucket: www.saulo.dev
  region: us-west-2
  local_dir: build
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - secure: oIxEKkTAatlGFRw/WK1aMLGhryH+ZSCyeg/+7CyiIjuYBnMc5EV96l4BQA6u2IhQKi/oEbX8vOuD59BGqkk2lfqL5excQ5XJ6WcDLL+5K1opCfn1XHUHU2OHWvugUOu5GxktV1JTOAdcAhCE0QiBloTa9bqLcCVmvjFnNDp8f3WNMkt2K+8HlTj27lW+ylZ+W7xMb2MlmnJ2js0VxBPJGytXVd5uQB024ROEDct4eMxNhOyO7jToAHW3B+Qxk426Ss6jvrblNkX+etFdwlJVI3v4h1Jg+meTvaIr2B8ZAj8Si2YHsrucstDsUFclNXrRXegLcqzUWTcvX3cEiVusOmA8jPCuDmHTuBo8bGyRoibl9M+hBzjcpXtz/btcmJWDf9AwEkPjUFK7z7VBepossO18JeXfh+2RGk4H8U9wvQrq7In6EVBd+huMQt1wJE+Xnqu1B3ooDMcno2Sy6ptqh5jL2mJIoFMkJNP/cuOdS8E8Y20codsd1Vi1S4EuJ++z+vaxryQdifOQTUihjLmCJAi6GgNgsRrQRC7IT/96UTrR+Or9duDUqBZD96x0U7vpz67nAUX9XFmcMCw/lAdiE3LC467MC9I2Q/x+oeWYwuIUPTeT/cop/jVJ1A1BhRRAWphzue2vn82Mh6D7D+gFLWZRgyHS8wZMkCPuycvkxjc=
  - secure: HqFEyTJHQ7IaZr9Kj9vTtzQZILRCypqHL7VH33e63cHK9AfyWRScQDH2VGrocBHr7LRIXDX/T8RByJNCfvCiTjXsQOc8ou32jcVho2M5OL8mW60qLXaiRyJ11esflx8kUqMnan2Wltjsmis8bkeA3csnIedCcD1ZJNk0Y+5FNUr8TOdjSPI+AHDHV0Pv9dLt2505VxgoVf4A7iaCJKUQ3ZOG1XvtZ8Daw3gbyvcOpNi3W2AoI42x4w1DW8XWMdHzraTnbYe0LAN+ZgU19N4lnQI7/Yw6jAyvOcyZsn4u5oZAmioJzl2liK3t8cNDjsv2GRybMkOka1t61mpis/n3+t7DqA6BYkp4AsQd1NmmlzSltJeIn3lGg8vIJnbUCQQZN0eawFgmpoJBEeFsgp6EscTa7aPCRZj/Ja9V+0T9erTlj6YwnRUVkiz6222UG16+3QyO4wdRJ3jCEKWOOfKbW7apAvkA8o/ETxImq9BaND9v6E88mc/TbQHNh2RiYANQXqGsaS/l/WraD06ON6WiMNPEGJEWJxdBPGbDDObXiedk+55Jq+XuTpEuUWUjhss9oCiT2+dr33nkecaoXp9zoZ99OocsbNb6e99BXqAFi/wiMLMtotGLrk0e/yDQgy0DH0QDuEQTM/xUh0jNCWsFsugJm24WXFrrce9d9FOiL6o=
