language: node_js
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
before_deploy: pip install --user awscli
deploy:
  provider: script
  script: bash scripts/s3-deploy.sh
  acl: public_read
  bucket: "$BUCKET_NAME"
  region: "$BUCKET_REGION"
  local_dir: build
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - BUCKET_NAME=saulo.dev
  - BUCKET_REGION=us-east-1
  - secure: DtakAyljCBvGQXf2f7vj2hfOSraJW/BV2ksBKkw251TltR6YFitKrRik8+iTNHlEwNCX+wkfEU00RmQigLLu7qgt+N5gSAXWdDM1ScAw5Ax6Ha1CzSaoXjMrsvL07IxAD1JTz/Gfl4A/hsm0XbOJ2/8hzmE6flyifyNJEtETMcKCE5ggjwDHCOYMNdZgcZo/xWnxUHaICNFxV6dOcSkL5mDCX3nCuJTsmdiagthrs9q3jwG6m4ishuAWCBOCtMdfD/I+xRxSUvS1dOFzzjL5ApQ/K3Cns2z3BvGBQY2bBv3A1p2pI8tV/yYMehHjqQLByU738/xQwNBkuzTcWfvmPy3+BZfZb3v892Mkhv5X9rRYCpeDiO0xwVRHtxE3DN7hEaXlDsB40uNxCDwL4ZjS7912HMzPhAbjAXvfxh8wOD6t1cdL1oJ8sNT52n32Ho/zSHqlA7HOOTF9pHVr+x9012JPu+aybKp+SwkxOUKDHo73T58LQxLiUTnd4rEScEtHwKCiS+OGDyZmv9aRAbcyTXbgWNRGC9LgGGL0HgA2WT6eJQxy6YM0nyYqfGOcQn7k2ilIc5vMCaBaOezYxWDDrl+CSyPv0mYwnHP+VuD1hyNy9fuL4N4RBY3pAT+4McllNyiglZqSjOudys+3gUlP8bAVnVPl/VzjAUIMqbuUHZE=
  - secure: XRf46tgj652ECxcpOAWwSOXTw6hqlaBiwxkxvG/xZ+Ub4lcU4wS1T47Ko1Avd/UGJ6nYD24eSg9sStEeh8CGvud4N6nrplyQN8Lz5fEL3Mi7ZHhi3oJLfck/aiHEBV76SCpwB/VaC4gx4JaWScXR40qqFi/7qMkfjmdf0P8j2H5lFt/Qdwc9H+iwSXBtaScfA1bunm4EZhk84SADXicPO38QZaFkvOef4OI4wIiVy63fTN3Q1GQzY9XA9SU35dIrK8lBW8veG4TtEF6JByMu7B04odnpaMxRY6VYm1MoDuvUeN0g+/nSfQagkTRBMhSJzo8Dcdsgwc8nkDQom5dUSlBm6oPAAUeWcM/cezk32+b81TvOEIjSkzomEb3kdIA456dvUl3ltqCue/y4FJGb1PvsGpqFl5fpznO8qhUlUk0urGdmDeB0O3t/xaqSdNVnVG24rq5nYSfcd4e5UhZbfqxJu6wryyJcbx/d/mTlBWEoxT59MI+rsr//osIIXNr+lSLxSclSpcrMOmWu4iTAN8ts/addQSFxvS1kofQ1N2HnN1vHA+05quqMwuxupbYbwTHLHKNHbo+qj/jUMiZxYfQipRcvyuu6qvxGeXbhqCwzrLk8Yh6SsX/C2QtQ7QTPpVp7kynY2+vW7/6BoaAerluAYLhiHE1ZIdiQjX6LVgU=
  - secure: g1KfSD4fh4xN7OqNmjgkeDdJh5JVoKFOMmPipueivDCrJZ5O6vM7RxhaydXB981ZpmGRrvAn8CJLFuO2Fn/3Ao97XS/qq+R5zyb4dWn4EZCjBjwklqZsICGTawSBt3a3JsixRwXZLWHj2ONeV0iYMfOKfE/l4LJw7IMxQp5jwDuc7t0VfwrIwg4nZqs4FcjJzL39AXwgjf2wleSN6wrFdoqIbjpi9Cgq0R0JwEL85wusmpOg3m7hfBeppzIg9YkftJcHgnQxybndbjHaP0TDVKt0+7Vq/GrY/XDS2bWyr1bdw+fKYi7Di1NviJoM5vYOZBaCjdH2ngYjzW7nEJwXwYVt8SH9lUBmLSrmNoFWCIk5M24WzjkbKGPxidnLB/JOOgb/ohBxDFn+WE1SdCF9cqgbF/xJueAR1oOG32+KjkWiuAKcJH9I28RMV8Oxd4GnyjPcxsENmdwmRL+stm53cbOatI1wafTsdeZfGlrWbdjoqd3aR7pLnZeQ3scB9Jj7b9PnXrOmVy88q/kTE9nOOPaTGBpfTTsnqHi7TBv5LZubIr4W0ShJyIL/gePGL6iD1nGBpsBgWU72FbegfhlknGBCrPdGEvp6JvCe/c6N2v6I6bVTgJ7OJpr3AdFRjTWQZlOLzLqS/ppq6wUMZWSzaw1o2xtTCna60TMQg/D5Px8=
  - secure: f0hMaFpbTTOKyy1ZaAn7s3KtolEBiq8PZBGILCugVRPUARAN6pNTysEWMNFwZkU0cVDZ/O0fbJT3BqqW6TxtB4zMnUBieacs5Nh1+7o88Dhe1NcYxmTV2TgjlSiiVVcBtyAVrV6sJIGG8sCFsONg9XowJ8YFtlt9fUiukCrWJUUriuu+LRkPkDmba4JtqK3o2OMk9dfhL52waSF3HBjPgADFf/Xs6IU+7nWqXU8dEcW5JxNZdcWkeEwjKjc2h/CuKkYpv7H8CBDe8Y7KFpFJYYQoXn7Y5lOhbc2Jposw+03FnkwRDsNZyP6jHinfh+WJss6K0y0Dbms+eaSd9lkji3FEN6VBlkEoUZaAinhtfMeiiSZAvRejdQhWqalOXIUHSf8T72CELeXS2ophcJyXuzFAAlpDxlzDzsMXoZbF/To8/k2zLdPajdOKkVhpojzddylGnblLwOMzoubAyo2mUFrXcznmK0oybXIIoqJKV3Six720MfnKjPSxXh1bv8MpDyhi66p2G+do97SVZEQCreXA3yrdrIzLE6YFTo/XiT7tb4LNOrUt1yMBjTGiYxrKHp4/sRmxJik+Yz2ZM8bmPijDmNAanE/kCxuRNaeHbQkrG8cTmzkP11js2aGhWFwVghC/WE7JOiAMjVb3M5MgE2QUaQHhREn6oVmdLWzRo9U=
